// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	CommentID  uuid.UUID
	PostID     pgtype.UUID
	AuthorID   pgtype.UUID
	Content    string
	PostedDate time.Time
	IsActive   pgtype.Bool
}

type Post struct {
	PostID       uuid.UUID
	Content      string
	IncidentDate pgtype.Date
	PostedDate   time.Time
	Latitude     float64
	Longtitude   float64
	AddressText  string
	Location     []byte
	IsActive     pgtype.Bool
}

type User struct {
	UserID       uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	LastLoginAt  time.Time
	IsActive     pgtype.Bool
}
