// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertNewPost = `-- name: InsertNewPost :exec
INSERT INTO posts (
    content,
    incident_date,
    latitude,
    longtitude,
    address_text,
    location
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    ST_SetSRID(ST_MakePoint($4, $3), 4326)
)
`

type InsertNewPostParams struct {
	Content      string
	IncidentDate pgtype.Date
	Latitude     *float64
	Longtitude   *float64
	AddressText  string
}

func (q *Queries) InsertNewPost(ctx context.Context, arg InsertNewPostParams) error {
	_, err := q.db.Exec(ctx, insertNewPost,
		arg.Content,
		arg.IncidentDate,
		arg.Latitude,
		arg.Longtitude,
		arg.AddressText,
	)
	return err
}

const selectPostInfo = `-- name: SelectPostInfo :one
SELECT post_id, content, incident_date, posted_date, address_text, latitude, longtitude, location
FROM posts
WHERE is_active = true
AND post_id = $1
`

type SelectPostInfoRow struct {
	PostID       uuid.UUID
	Content      string
	IncidentDate pgtype.Date
	PostedDate   time.Time
	AddressText  string
	Latitude     *float64
	Longtitude   *float64
	Location     []byte
}

func (q *Queries) SelectPostInfo(ctx context.Context, postID uuid.UUID) (SelectPostInfoRow, error) {
	row := q.db.QueryRow(ctx, selectPostInfo, postID)
	var i SelectPostInfoRow
	err := row.Scan(
		&i.PostID,
		&i.Content,
		&i.IncidentDate,
		&i.PostedDate,
		&i.AddressText,
		&i.Latitude,
		&i.Longtitude,
		&i.Location,
	)
	return i, err
}

const selectPosts = `-- name: SelectPosts :many
SELECT post_id, posted_date, address_text, latitude, longtitude, location
FROM posts
WHERE is_active = true
ORDER BY posted_date DESC
LIMIT 50
`

type SelectPostsRow struct {
	PostID      uuid.UUID
	PostedDate  time.Time
	AddressText string
	Latitude    *float64
	Longtitude  *float64
	Location    []byte
}

func (q *Queries) SelectPosts(ctx context.Context) ([]SelectPostsRow, error) {
	rows, err := q.db.Query(ctx, selectPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectPostsRow
	for rows.Next() {
		var i SelectPostsRow
		if err := rows.Scan(
			&i.PostID,
			&i.PostedDate,
			&i.AddressText,
			&i.Latitude,
			&i.Longtitude,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
