// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertNewAccount = `-- name: InsertNewAccount :exec
INSERT INTO users (
    username,
    email,
    password_hash,
    last_login_at
) VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type InsertNewAccountParams struct {
	Username     string
	Email        string
	PasswordHash string
	LastLoginAt  time.Time
}

func (q *Queries) InsertNewAccount(ctx context.Context, arg InsertNewAccountParams) error {
	_, err := q.db.Exec(ctx, insertNewAccount,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.LastLoginAt,
	)
	return err
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE users
SET 
    username = $2,
    email = $3, 
    password_hash = $4
WHERE user_id = $1
`

type UpdateAccountParams struct {
	UserID       uuid.UUID
	Username     string
	Email        string
	PasswordHash string
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.Exec(ctx, updateAccount,
		arg.UserID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	return err
}
