// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlers

import (
	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// GetPosts provides a mock function for the type MockHandler
func (_mock *MockHandler) GetPosts(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockHandler_GetPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPosts'
type MockHandler_GetPosts_Call struct {
	*mock.Call
}

// GetPosts is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockHandler_Expecter) GetPosts(c interface{}) *MockHandler_GetPosts_Call {
	return &MockHandler_GetPosts_Call{Call: _e.mock.On("GetPosts", c)}
}

func (_c *MockHandler_GetPosts_Call) Run(run func(c *gin.Context)) *MockHandler_GetPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHandler_GetPosts_Call) Return() *MockHandler_GetPosts_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_GetPosts_Call) RunAndReturn(run func(c *gin.Context)) *MockHandler_GetPosts_Call {
	_c.Run(run)
	return _c
}
