// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositories

import (
	"context"

	"github.com/cloneOsima/bigLand/backend/internal/sqlc"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPostRepository creates a new instance of MockPostRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostRepository {
	mock := &MockPostRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostRepository is an autogenerated mock type for the PostRepository type
type MockPostRepository struct {
	mock.Mock
}

type MockPostRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostRepository) EXPECT() *MockPostRepository_Expecter {
	return &MockPostRepository_Expecter{mock: &_m.Mock}
}

// CreatePost provides a mock function for the type MockPostRepository
func (_mock *MockPostRepository) CreatePost(dbCtx context.Context, info sqlc.CreatePostParams) error {
	ret := _mock.Called(dbCtx, info)

	if len(ret) == 0 {
		panic("no return value specified for CreatePost")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreatePostParams) error); ok {
		r0 = returnFunc(dbCtx, info)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostRepository_CreatePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePost'
type MockPostRepository_CreatePost_Call struct {
	*mock.Call
}

// CreatePost is a helper method to define mock.On call
//   - dbCtx context.Context
//   - info sqlc.CreatePostParams
func (_e *MockPostRepository_Expecter) CreatePost(dbCtx interface{}, info interface{}) *MockPostRepository_CreatePost_Call {
	return &MockPostRepository_CreatePost_Call{Call: _e.mock.On("CreatePost", dbCtx, info)}
}

func (_c *MockPostRepository_CreatePost_Call) Run(run func(dbCtx context.Context, info sqlc.CreatePostParams)) *MockPostRepository_CreatePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CreatePostParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CreatePostParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostRepository_CreatePost_Call) Return(err error) *MockPostRepository_CreatePost_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostRepository_CreatePost_Call) RunAndReturn(run func(dbCtx context.Context, info sqlc.CreatePostParams) error) *MockPostRepository_CreatePost_Call {
	_c.Call.Return(run)
	return _c
}

// GetPostInfo provides a mock function for the type MockPostRepository
func (_mock *MockPostRepository) GetPostInfo(ctx context.Context, postID uuid.UUID) (sqlc.GetPostInfoRow, error) {
	ret := _mock.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for GetPostInfo")
	}

	var r0 sqlc.GetPostInfoRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (sqlc.GetPostInfoRow, error)); ok {
		return returnFunc(ctx, postID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) sqlc.GetPostInfoRow); ok {
		r0 = returnFunc(ctx, postID)
	} else {
		r0 = ret.Get(0).(sqlc.GetPostInfoRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostRepository_GetPostInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPostInfo'
type MockPostRepository_GetPostInfo_Call struct {
	*mock.Call
}

// GetPostInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - postID uuid.UUID
func (_e *MockPostRepository_Expecter) GetPostInfo(ctx interface{}, postID interface{}) *MockPostRepository_GetPostInfo_Call {
	return &MockPostRepository_GetPostInfo_Call{Call: _e.mock.On("GetPostInfo", ctx, postID)}
}

func (_c *MockPostRepository_GetPostInfo_Call) Run(run func(ctx context.Context, postID uuid.UUID)) *MockPostRepository_GetPostInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostRepository_GetPostInfo_Call) Return(getPostInfoRow sqlc.GetPostInfoRow, err error) *MockPostRepository_GetPostInfo_Call {
	_c.Call.Return(getPostInfoRow, err)
	return _c
}

func (_c *MockPostRepository_GetPostInfo_Call) RunAndReturn(run func(ctx context.Context, postID uuid.UUID) (sqlc.GetPostInfoRow, error)) *MockPostRepository_GetPostInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetPosts provides a mock function for the type MockPostRepository
func (_mock *MockPostRepository) GetPosts(ctx context.Context) ([]sqlc.GetPostsRow, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPosts")
	}

	var r0 []sqlc.GetPostsRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]sqlc.GetPostsRow, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []sqlc.GetPostsRow); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.GetPostsRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostRepository_GetPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPosts'
type MockPostRepository_GetPosts_Call struct {
	*mock.Call
}

// GetPosts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPostRepository_Expecter) GetPosts(ctx interface{}) *MockPostRepository_GetPosts_Call {
	return &MockPostRepository_GetPosts_Call{Call: _e.mock.On("GetPosts", ctx)}
}

func (_c *MockPostRepository_GetPosts_Call) Run(run func(ctx context.Context)) *MockPostRepository_GetPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPostRepository_GetPosts_Call) Return(getPostsRows []sqlc.GetPostsRow, err error) *MockPostRepository_GetPosts_Call {
	_c.Call.Return(getPostsRows, err)
	return _c
}

func (_c *MockPostRepository_GetPosts_Call) RunAndReturn(run func(ctx context.Context) ([]sqlc.GetPostsRow, error)) *MockPostRepository_GetPosts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// DeleteAccount provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) DeleteAccount() {
	_mock.Called()
	return
}

// MockUserRepository_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type MockUserRepository_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
func (_e *MockUserRepository_Expecter) DeleteAccount() *MockUserRepository_DeleteAccount_Call {
	return &MockUserRepository_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount")}
}

func (_c *MockUserRepository_DeleteAccount_Call) Run(run func()) *MockUserRepository_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserRepository_DeleteAccount_Call) Return() *MockUserRepository_DeleteAccount_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUserRepository_DeleteAccount_Call) RunAndReturn(run func()) *MockUserRepository_DeleteAccount_Call {
	_c.Run(run)
	return _c
}

// Login provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Login() {
	_mock.Called()
	return
}

// MockUserRepository_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockUserRepository_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
func (_e *MockUserRepository_Expecter) Login() *MockUserRepository_Login_Call {
	return &MockUserRepository_Login_Call{Call: _e.mock.On("Login")}
}

func (_c *MockUserRepository_Login_Call) Run(run func()) *MockUserRepository_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserRepository_Login_Call) Return() *MockUserRepository_Login_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUserRepository_Login_Call) RunAndReturn(run func()) *MockUserRepository_Login_Call {
	_c.Run(run)
	return _c
}

// Logout provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Logout() {
	_mock.Called()
	return
}

// MockUserRepository_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockUserRepository_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
func (_e *MockUserRepository_Expecter) Logout() *MockUserRepository_Logout_Call {
	return &MockUserRepository_Logout_Call{Call: _e.mock.On("Logout")}
}

func (_c *MockUserRepository_Logout_Call) Run(run func()) *MockUserRepository_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserRepository_Logout_Call) Return() *MockUserRepository_Logout_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUserRepository_Logout_Call) RunAndReturn(run func()) *MockUserRepository_Logout_Call {
	_c.Run(run)
	return _c
}

// NewAccount provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) NewAccount() {
	_mock.Called()
	return
}

// MockUserRepository_NewAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewAccount'
type MockUserRepository_NewAccount_Call struct {
	*mock.Call
}

// NewAccount is a helper method to define mock.On call
func (_e *MockUserRepository_Expecter) NewAccount() *MockUserRepository_NewAccount_Call {
	return &MockUserRepository_NewAccount_Call{Call: _e.mock.On("NewAccount")}
}

func (_c *MockUserRepository_NewAccount_Call) Run(run func()) *MockUserRepository_NewAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserRepository_NewAccount_Call) Return() *MockUserRepository_NewAccount_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUserRepository_NewAccount_Call) RunAndReturn(run func()) *MockUserRepository_NewAccount_Call {
	_c.Run(run)
	return _c
}
