// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"context"

	"github.com/cloneOsima/bigLand/backend/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPostService creates a new instance of MockPostService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostService {
	mock := &MockPostService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostService is an autogenerated mock type for the PostService type
type MockPostService struct {
	mock.Mock
}

type MockPostService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostService) EXPECT() *MockPostService_Expecter {
	return &MockPostService_Expecter{mock: &_m.Mock}
}

// GetPostInfo provides a mock function for the type MockPostService
func (_mock *MockPostService) GetPostInfo(ctx context.Context, postID string) (*models.Post, error) {
	ret := _mock.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for GetPostInfo")
	}

	var r0 *models.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Post, error)); ok {
		return returnFunc(ctx, postID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Post); ok {
		r0 = returnFunc(ctx, postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostService_GetPostInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPostInfo'
type MockPostService_GetPostInfo_Call struct {
	*mock.Call
}

// GetPostInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - postID string
func (_e *MockPostService_Expecter) GetPostInfo(ctx interface{}, postID interface{}) *MockPostService_GetPostInfo_Call {
	return &MockPostService_GetPostInfo_Call{Call: _e.mock.On("GetPostInfo", ctx, postID)}
}

func (_c *MockPostService_GetPostInfo_Call) Run(run func(ctx context.Context, postID string)) *MockPostService_GetPostInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostService_GetPostInfo_Call) Return(post *models.Post, err error) *MockPostService_GetPostInfo_Call {
	_c.Call.Return(post, err)
	return _c
}

func (_c *MockPostService_GetPostInfo_Call) RunAndReturn(run func(ctx context.Context, postID string) (*models.Post, error)) *MockPostService_GetPostInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetPosts provides a mock function for the type MockPostService
func (_mock *MockPostService) GetPosts(ctx context.Context) ([]*models.Posts, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPosts")
	}

	var r0 []*models.Posts
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*models.Posts, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*models.Posts); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Posts)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostService_GetPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPosts'
type MockPostService_GetPosts_Call struct {
	*mock.Call
}

// GetPosts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPostService_Expecter) GetPosts(ctx interface{}) *MockPostService_GetPosts_Call {
	return &MockPostService_GetPosts_Call{Call: _e.mock.On("GetPosts", ctx)}
}

func (_c *MockPostService_GetPosts_Call) Run(run func(ctx context.Context)) *MockPostService_GetPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPostService_GetPosts_Call) Return(postss []*models.Posts, err error) *MockPostService_GetPosts_Call {
	_c.Call.Return(postss, err)
	return _c
}

func (_c *MockPostService_GetPosts_Call) RunAndReturn(run func(ctx context.Context) ([]*models.Posts, error)) *MockPostService_GetPosts_Call {
	_c.Call.Return(run)
	return _c
}

// NewPost provides a mock function for the type MockPostService
func (_mock *MockPostService) NewPost(ctx context.Context, inputValue *models.Post) error {
	ret := _mock.Called(ctx, inputValue)

	if len(ret) == 0 {
		panic("no return value specified for NewPost")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Post) error); ok {
		r0 = returnFunc(ctx, inputValue)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostService_NewPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewPost'
type MockPostService_NewPost_Call struct {
	*mock.Call
}

// NewPost is a helper method to define mock.On call
//   - ctx context.Context
//   - inputValue *models.Post
func (_e *MockPostService_Expecter) NewPost(ctx interface{}, inputValue interface{}) *MockPostService_NewPost_Call {
	return &MockPostService_NewPost_Call{Call: _e.mock.On("NewPost", ctx, inputValue)}
}

func (_c *MockPostService_NewPost_Call) Run(run func(ctx context.Context, inputValue *models.Post)) *MockPostService_NewPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Post
		if args[1] != nil {
			arg1 = args[1].(*models.Post)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostService_NewPost_Call) Return(err error) *MockPostService_NewPost_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostService_NewPost_Call) RunAndReturn(run func(ctx context.Context, inputValue *models.Post) error) *MockPostService_NewPost_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// SignUp provides a mock function for the type MockUserService
func (_mock *MockUserService) SignUp(ctx context.Context, data models.User) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for SignUp")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.User) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_SignUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignUp'
type MockUserService_SignUp_Call struct {
	*mock.Call
}

// SignUp is a helper method to define mock.On call
//   - ctx context.Context
//   - data models.User
func (_e *MockUserService_Expecter) SignUp(ctx interface{}, data interface{}) *MockUserService_SignUp_Call {
	return &MockUserService_SignUp_Call{Call: _e.mock.On("SignUp", ctx, data)}
}

func (_c *MockUserService_SignUp_Call) Run(run func(ctx context.Context, data models.User)) *MockUserService_SignUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.User
		if args[1] != nil {
			arg1 = args[1].(models.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_SignUp_Call) Return(err error) *MockUserService_SignUp_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_SignUp_Call) RunAndReturn(run func(ctx context.Context, data models.User) error) *MockUserService_SignUp_Call {
	_c.Call.Return(run)
	return _c
}
